# .goreleaser.yml
builds:
  # You can have multiple builds defined as a yaml list
  -

    # Path to main.go file or main package.
    # Default is `.`.
    main: ./service/main.go
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - linux

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
